cp -r -p ../qml ./release
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\qml\quick2\Release\QtGStreamerQuick2.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Release\release\qml\quick2\QtGStreamer\QtGStreamerQuick2.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\qml\quick2\Release\QtGStreamerQuick2.pdb C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Release\release\qml\quick2\QtGStreamer\QtGStreamerQuick2.pdb
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\QGlib\Release\Qt5GLib-2.0.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Release\release\Qt5GLib-2.0.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\QGst\Release\Qt5GStreamer-1.0.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Release\release\Qt5GStreamer-1.0.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\QGst\Release\Qt5GStreamerQuick-1.0.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Release\release\Qt5GStreamerQuick-1.0.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\QGst\Release\Qt5GStreamerUi-1.0.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Release\release\Qt5GStreamerUi-1.0.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\QGst\Release\Qt5GStreamerUtils-1.0.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Release\release\Qt5GStreamerUtils-1.0.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\elements\gstqtvideosink\Release\gstqt5videosink.dll  C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Release\release\gstqt5videosink.dll 
cp -p C:\Users\papa\QtGStreamerHUDApp\sony_remote_camera_cpp_drivers-dev\Release\sony_capture.dll  C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Release\release\sony_capture.dll 
cp -p C:\Users\papa\QtGStreamerHUDApp\sony_remote_camera_cpp_drivers-dev\Release\sony_capture.pdb  C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Release\release\sony_capture.pdb
