cp -r -p ../qml ./debug
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\qml\quick2\Debug\QtGStreamerQuick2.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\debug\qml\quick2\QtGStreamer\QtGStreamerQuick2.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\qml\quick2\Debug\QtGStreamerQuick2.pdb C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\debug\qml\quick2\QtGStreamer\QtGStreamerQuick2.pdb
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\QGlib\Debug\Qt5GLib-2.0.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\debug\Qt5GLib-2.0.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\QGst\Debug\Qt5GStreamer-1.0.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\debug\Qt5GStreamer-1.0.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\QGst\Debug\Qt5GStreamerQuick-1.0.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\debug\Qt5GStreamerQuick-1.0.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\QGst\Debug\Qt5GStreamerUi-1.0.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\debug\Qt5GStreamerUi-1.0.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\src\QGst\Debug\Qt5GStreamerUtils-1.0.dll C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\debug\Qt5GStreamerUtils-1.0.dll
cp -p C:\qt-gstreamer-1.2.0\build-qt5.9.1\elements\gstqtvideosink\Debug\gstqt5videosink.dll  C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\debug\gstqt5videosink.dll 
cp -p C:\Users\papa\QtGStreamerHUDApp\sony_remote_camera_cpp_drivers-dev\Debug\sony_capture.dll  C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\debug\sony_capture.dll 
cp -p C:\Users\papa\QtGStreamerHUDApp\sony_remote_camera_cpp_drivers-dev\Debug\sony_capture.pdb  C:\Users\papa\QtGStreamerHUDAppVR\build-QtGStreamerHUDApp_5.4.1-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\debug\sony_capture.pdb
